/**
 * Route map — web, app, and admin paths for the pastour → Next.js migration.
 */

export const ROUTES = {
  web: {
    home: '/',
    contact: '/contact',
    privacy: '/privacy',
    nursing: '/nursing',
    laser: '/laser',
    gallery: '/gallery',
    partners: '/partners',
    consultation: '/consultation',
    club: '/club',
    wallet: '/wallet',
    reminders: '/reminders',
    medical: '/medical',
    medicalSpecialty: '/medical/specialty',
    medicalDoctors: '/medical/doctors',
    dental: '/dental',
    dentalGeneral: '/dental/general',
    dentalSpecialty: '/dental/specialty',
    dentalEducation: '/dental/education',
    dentalBooking: '/dental/booking',
    dentalConfirm: '/dental/confirm',
    dentalSuccess: '/dental/success',
    dentalFailed: '/dental/failed',
    dentalMembership: '/dental/membership',
    shop: '/shop',
    shopVip: '/shop/vip',
    shopCatalog: '/shop/catalog',
    shopCart: '/shop/cart',
    shopSuccess: '/shop/success',
    shopFacility: '/shop/facility',
  },
  app: {
    home: '/app',
    contact: '/app/contact',
    privacy: '/app/privacy',
    nursing: '/app/nursing',
    laser: '/app/laser',
    gallery: '/app/gallery',
    partners: '/app/partners',
    consultation: '/app/consultation',
    club: '/app/club',
    wallet: '/app/wallet',
    reminders: '/app/reminders',
    medical: '/app/medical',
    medicalSpecialty: '/app/medical/specialty',
    medicalDoctors: '/app/medical/doctors',
    dental: '/app/dental',
    dentalGeneral: '/app/dental/general',
    dentalSpecialty: '/app/dental/specialty',
    dentalEducation: '/app/dental/education',
    dentalBooking: '/app/dental/booking',
    dentalConfirm: '/app/dental/confirm',
    dentalSuccess: '/app/dental/success',
    dentalFailed: '/app/dental/failed',
    dentalMembership: '/app/dental/membership',
    shop: '/app/shop',
    shopVip: '/app/shop-vip',
    shopCatalog: '/app/shop-catalog',
    shopCart: '/app/shop-cart',
    shopSuccess: '/app/shop-success',
    shopFacility: '/app/shop-facility',
  },
  admin: {
    login: '/admin/login',
    dashboard: '/admin',
    bookings: '/admin/bookings',
    consultations: '/admin/consultations',
    reminders: '/admin/reminders',
    services: '/admin/services',
    club: '/admin/club',
    gallery: '/admin/gallery',
    visitors: '/admin/visitors',
    commissions: '/admin/commissions',
    facilities: '/admin/facilities',
    partners: '/admin/partners',
    doctors: '/admin/doctors',
    memberships: '/admin/memberships',
    laserServices: '/admin/laser-services',
    nursingServices: '/admin/nursing-services',
    wallets: '/admin/wallets',
    consultationPrices: '/admin/consultation-prices',
    shop: '/admin/shop',
  },
} as const;

export type WebRouteKey = keyof typeof ROUTES.web;
export type AppRouteKey = keyof typeof ROUTES.app;
export type AdminRouteKey = keyof typeof ROUTES.admin;
export type Routes = typeof ROUTES;
