/**
 * Route map — web, app, and admin paths for the pastour → Next.js migration.
 */

export const ROUTES = {
  web: {
    home: '/',
    contact: '/contact',
    privacy: '/privacy',
    nursing: '/nursing',
    nursingConfirm: '/nursing/confirm',
    nursingSuccess: '/nursing/success',
    nursingFailed: '/nursing/failed',
    laser: '/laser',
    laserConfirm: '/laser/confirm',
    laserSuccess: '/laser/success',
    laserFailed: '/laser/failed',
    gallery: '/gallery',
    partners: '/partners',
    consultation: '/consultation',
    consultationConfirm: '/consultation/confirm',
    consultationSuccess: '/consultation/success',
    consultationFailed: '/consultation/failed',
    club: '/club',
    wallet: '/wallet',
    reminders: '/reminders',
    account: '/account',
    help: '/help',
    complaints: '/complaints',
    support: '/support',
    installments: '/installments',
    medical: '/medical',
    medicalSpecialty: '/medical/specialty',
    medicalDoctors: '/medical/doctors',
    dental: '/dental',
    dentalGeneral: '/dental/general',
    dentalSpecialty: '/dental/specialty',
    dentalEducation: '/dental/education',
    dentalBooking: '/dental/booking',
    dentalConfirm: '/dental/confirm',
    dentalSuccess: '/dental/success',
    dentalFailed: '/dental/failed',
    dentalMembership: '/dental/membership',
    shop: '/shop',
    shopVip: '/shop/vip',
    shopCatalog: '/shop/catalog',
    shopCart: '/shop/cart',
    shopSuccess: '/shop/success',
    shopFailed: '/shop/failed',
    shopFacility: '/shop/facility',
  },
  app: {
    home: '/app',
    contact: '/app/contact',
    privacy: '/app/privacy',
    nursing: '/app/nursing',
    nursingConfirm: '/app/nursing/confirm',
    nursingSuccess: '/app/nursing/success',
    nursingFailed: '/app/nursing/failed',
    laser: '/app/laser',
    laserConfirm: '/app/laser/confirm',
    laserSuccess: '/app/laser/success',
    laserFailed: '/app/laser/failed',
    gallery: '/app/gallery',
    partners: '/app/partners',
    consultation: '/app/consultation',
    consultationConfirm: '/app/consultation/confirm',
    consultationSuccess: '/app/consultation/success',
    consultationFailed: '/app/consultation/failed',
    club: '/app/club',
    wallet: '/app/wallet',
    reminders: '/app/reminders',
    account: '/app/account',
    help: '/app/help',
    complaints: '/app/complaints',
    support: '/app/support',
    installments: '/app/installments',
    medical: '/app/medical',
    medicalSpecialty: '/app/medical/specialty',
    medicalDoctors: '/app/medical/doctors',
    dental: '/app/dental',
    dentalGeneral: '/app/dental/general',
    dentalSpecialty: '/app/dental/specialty',
    dentalEducation: '/app/dental/education',
    dentalBooking: '/app/dental/booking',
    dentalConfirm: '/app/dental/confirm',
    dentalSuccess: '/app/dental/success',
    dentalFailed: '/app/dental/failed',
    dentalMembership: '/app/dental/membership',
    shop: '/app/shop',
    shopVip: '/app/shop-vip',
    shopCatalog: '/app/shop-catalog',
    shopCart: '/app/shop-cart',
    shopSuccess: '/app/shop-success',
    shopFailed: '/app/shop-failed',
    shopFacility: '/app/shop-facility',
  },
  admin: {
    login: '/admin/login',
    dashboard: '/admin',
    bookings: '/admin/bookings',
    consultations: '/admin/consultations',
    reminders: '/admin/reminders',
    services: '/admin/services',
    dentalEducation: '/admin/dental-education',
    club: '/admin/club',
    gallery: '/admin/gallery',
    visitors: '/admin/visitors',
    commissions: '/admin/commissions',
    facilities: '/admin/facilities',
    partners: '/admin/partners',
    doctors: '/admin/doctors',
    memberships: '/admin/memberships',
    laserServices: '/admin/laser-services',
    nursingServices: '/admin/nursing-services',
    wallets: '/admin/wallets',
    consultationPrices: '/admin/consultation-prices',
    shop: '/admin/shop',
    access: '/admin/access',
    patients: '/admin/patients',
    insurances: '/admin/insurances',
    reviews: '/admin/reviews',
    complaints: '/admin/complaints',
    support: '/admin/support',
    help: '/admin/help',
    installments: '/admin/installments',
  },
} as const;

export type WebRouteKey = keyof typeof ROUTES.web;
export type AppRouteKey = keyof typeof ROUTES.app;
export type AdminRouteKey = keyof typeof ROUTES.admin;
export type Routes = typeof ROUTES;
